import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { City } from '../../../cities/entities/city.entity';

@Injectable()
export class CitiesSeed {
  constructor(
    @InjectRepository(City)
    private readonly cityRepository: Repository<City>,
  ) {}

  async run() {
    const cities = [
      {
        name: 'Adana',
        code: '01',
        region: 'Akdeniz',
        latitude: 37.0,
        longitude: 35.3213,
      },
      {
        name: 'Adıyaman',
        code: '02',
        region: 'Güneydoğu Anadolu',
        latitude: 37.7648,
        longitude: 38.2786,
      },
      {
        name: 'Afyonkarahisar',
        code: '03',
        region: 'Ege',
        latitude: 38.7507,
        longitude: 30.5567,
      },
      {
        name: 'Ağrı',
        code: '04',
        region: 'Doğu Anadolu',
        latitude: 39.7191,
        longitude: 43.0503,
      },
      {
        name: 'Amasya',
        code: '05',
        region: 'Karadeniz',
        latitude: 40.6499,
        longitude: 35.8353,
      },
      {
        name: 'Ankara',
        code: '06',
        region: 'İç Anadolu',
        latitude: 39.9208,
        longitude: 32.8541,
      },
      {
        name: 'Antalya',
        code: '07',
        region: 'Akdeniz',
        latitude: 36.8841,
        longitude: 30.7056,
      },
      {
        name: 'Artvin',
        code: '08',
        region: 'Karadeniz',
        latitude: 41.1828,
        longitude: 41.8183,
      },
      {
        name: 'Aydın',
        code: '09',
        region: 'Ege',
        latitude: 37.856,
        longitude: 27.8416,
      },
      {
        name: 'Balıkesir',
        code: '10',
        region: 'Marmara',
        latitude: 39.6484,
        longitude: 27.8826,
      },
      {
        name: 'Bilecik',
        code: '11',
        region: 'Marmara',
        latitude: 40.1501,
        longitude: 29.983,
      },
      {
        name: 'Bingöl',
        code: '12',
        region: 'Doğu Anadolu',
        latitude: 38.8854,
        longitude: 40.4986,
      },
      {
        name: 'Bitlis',
        code: '13',
        region: 'Doğu Anadolu',
        latitude: 38.4006,
        longitude: 42.1088,
      },
      {
        name: 'Bolu',
        code: '14',
        region: 'Karadeniz',
        latitude: 40.7396,
        longitude: 31.611,
      },
      {
        name: 'Burdur',
        code: '15',
        region: 'Akdeniz',
        latitude: 37.7269,
        longitude: 30.2889,
      },
      {
        name: 'Bursa',
        code: '16',
        region: 'Marmara',
        latitude: 40.1824,
        longitude: 29.067,
      },
      {
        name: 'Çanakkale',
        code: '17',
        region: 'Marmara',
        latitude: 40.1553,
        longitude: 26.4142,
      },
      {
        name: 'Çankırı',
        code: '18',
        region: 'İç Anadolu',
        latitude: 40.6013,
        longitude: 33.6134,
      },
      {
        name: 'Çorum',
        code: '19',
        region: 'Karadeniz',
        latitude: 40.5506,
        longitude: 34.9556,
      },
      {
        name: 'Denizli',
        code: '20',
        region: 'Ege',
        latitude: 37.7765,
        longitude: 29.0864,
      },
      {
        name: 'Diyarbakır',
        code: '21',
        region: 'Güneydoğu Anadolu',
        latitude: 37.9144,
        longitude: 40.2306,
      },
      {
        name: 'Edirne',
        code: '22',
        region: 'Marmara',
        latitude: 41.6818,
        longitude: 26.5623,
      },
      {
        name: 'Elazığ',
        code: '23',
        region: 'Doğu Anadolu',
        latitude: 38.681,
        longitude: 39.2264,
      },
      {
        name: 'Erzincan',
        code: '24',
        region: 'Doğu Anadolu',
        latitude: 39.75,
        longitude: 39.5,
      },
      {
        name: 'Erzurum',
        code: '25',
        region: 'Doğu Anadolu',
        latitude: 39.9,
        longitude: 41.27,
      },
      {
        name: 'Eskişehir',
        code: '26',
        region: 'İç Anadolu',
        latitude: 39.7767,
        longitude: 30.5206,
      },
      {
        name: 'Gaziantep',
        code: '27',
        region: 'Güneydoğu Anadolu',
        latitude: 37.0662,
        longitude: 37.3833,
      },
      {
        name: 'Giresun',
        code: '28',
        region: 'Karadeniz',
        latitude: 40.9128,
        longitude: 38.3895,
      },
      {
        name: 'Gümüşhane',
        code: '29',
        region: 'Karadeniz',
        latitude: 40.4386,
        longitude: 39.5086,
      },
      {
        name: 'Hakkari',
        code: '30',
        region: 'Doğu Anadolu',
        latitude: 37.5833,
        longitude: 43.7333,
      },
      {
        name: 'Hatay',
        code: '31',
        region: 'Akdeniz',
        latitude: 36.4018,
        longitude: 36.3498,
      },
      {
        name: 'Isparta',
        code: '32',
        region: 'Akdeniz',
        latitude: 37.7648,
        longitude: 30.5566,
      },
      {
        name: 'Mersin',
        code: '33',
        region: 'Akdeniz',
        latitude: 36.8,
        longitude: 34.6333,
      },
      {
        name: 'İstanbul',
        code: '34',
        region: 'Marmara',
        latitude: 41.0082,
        longitude: 28.9784,
      },
      {
        name: 'İzmir',
        code: '35',
        region: 'Ege',
        latitude: 38.4192,
        longitude: 27.1287,
      },
      {
        name: 'Kars',
        code: '36',
        region: 'Doğu Anadolu',
        latitude: 40.6167,
        longitude: 43.1,
      },
      {
        name: 'Kastamonu',
        code: '37',
        region: 'Karadeniz',
        latitude: 41.3887,
        longitude: 33.7827,
      },
      {
        name: 'Kayseri',
        code: '38',
        region: 'İç Anadolu',
        latitude: 38.7312,
        longitude: 35.4787,
      },
      {
        name: 'Kırklareli',
        code: '39',
        region: 'Marmara',
        latitude: 41.7333,
        longitude: 27.2167,
      },
      {
        name: 'Kırşehir',
        code: '40',
        region: 'İç Anadolu',
        latitude: 39.1425,
        longitude: 34.1709,
      },
      {
        name: 'Kocaeli',
        code: '41',
        region: 'Marmara',
        latitude: 40.8533,
        longitude: 29.8815,
      },
      {
        name: 'Konya',
        code: '42',
        region: 'İç Anadolu',
        latitude: 37.8667,
        longitude: 32.4833,
      },
      {
        name: 'Kütahya',
        code: '43',
        region: 'Ege',
        latitude: 39.4167,
        longitude: 29.9833,
      },
      {
        name: 'Malatya',
        code: '44',
        region: 'Doğu Anadolu',
        latitude: 38.3552,
        longitude: 38.3095,
      },
      {
        name: 'Manisa',
        code: '45',
        region: 'Ege',
        latitude: 38.6191,
        longitude: 27.4289,
      },
      {
        name: 'Kahramanmaraş',
        code: '46',
        region: 'Akdeniz',
        latitude: 37.5858,
        longitude: 36.9371,
      },
      {
        name: 'Mardin',
        code: '47',
        region: 'Güneydoğu Anadolu',
        latitude: 37.3212,
        longitude: 40.7245,
      },
      {
        name: 'Muğla',
        code: '48',
        region: 'Ege',
        latitude: 37.2153,
        longitude: 28.3636,
      },
      {
        name: 'Muş',
        code: '49',
        region: 'Doğu Anadolu',
        latitude: 38.7432,
        longitude: 41.5065,
      },
      {
        name: 'Nevşehir',
        code: '50',
        region: 'İç Anadolu',
        latitude: 38.6244,
        longitude: 34.7144,
      },
      {
        name: 'Niğde',
        code: '51',
        region: 'İç Anadolu',
        latitude: 37.9667,
        longitude: 34.6833,
      },
      {
        name: 'Ordu',
        code: '52',
        region: 'Karadeniz',
        latitude: 40.9839,
        longitude: 37.8764,
      },
      {
        name: 'Rize',
        code: '53',
        region: 'Karadeniz',
        latitude: 41.0201,
        longitude: 40.5234,
      },
      {
        name: 'Sakarya',
        code: '54',
        region: 'Marmara',
        latitude: 40.7569,
        longitude: 30.3783,
      },
      {
        name: 'Samsun',
        code: '55',
        region: 'Karadeniz',
        latitude: 41.2867,
        longitude: 36.33,
      },
      {
        name: 'Siirt',
        code: '56',
        region: 'Güneydoğu Anadolu',
        latitude: 37.9333,
        longitude: 41.95,
      },
      {
        name: 'Sinop',
        code: '57',
        region: 'Karadeniz',
        latitude: 42.0231,
        longitude: 35.1531,
      },
      {
        name: 'Sivas',
        code: '58',
        region: 'İç Anadolu',
        latitude: 39.7477,
        longitude: 37.0179,
      },
      {
        name: 'Tekirdağ',
        code: '59',
        region: 'Marmara',
        latitude: 40.9833,
        longitude: 27.5167,
      },
      {
        name: 'Tokat',
        code: '60',
        region: 'Karadeniz',
        latitude: 40.3167,
        longitude: 36.55,
      },
      {
        name: 'Trabzon',
        code: '61',
        region: 'Karadeniz',
        latitude: 41.0015,
        longitude: 39.7178,
      },
      {
        name: 'Tunceli',
        code: '62',
        region: 'Doğu Anadolu',
        latitude: 39.1079,
        longitude: 39.5401,
      },
      {
        name: 'Şanlıurfa',
        code: '63',
        region: 'Güneydoğu Anadolu',
        latitude: 37.1591,
        longitude: 38.7969,
      },
      {
        name: 'Uşak',
        code: '64',
        region: 'Ege',
        latitude: 38.6823,
        longitude: 29.4082,
      },
      {
        name: 'Van',
        code: '65',
        region: 'Doğu Anadolu',
        latitude: 38.4891,
        longitude: 43.4089,
      },
      {
        name: 'Yozgat',
        code: '66',
        region: 'İç Anadolu',
        latitude: 39.8181,
        longitude: 34.8147,
      },
      {
        name: 'Zonguldak',
        code: '67',
        region: 'Karadeniz',
        latitude: 41.4564,
        longitude: 31.7987,
      },
      {
        name: 'Aksaray',
        code: '68',
        region: 'İç Anadolu',
        latitude: 38.3687,
        longitude: 34.037,
      },
      {
        name: 'Bayburt',
        code: '69',
        region: 'Karadeniz',
        latitude: 40.2552,
        longitude: 40.2249,
      },
      {
        name: 'Karaman',
        code: '70',
        region: 'İç Anadolu',
        latitude: 37.1759,
        longitude: 33.2287,
      },
      {
        name: 'Kırıkkale',
        code: '71',
        region: 'İç Anadolu',
        latitude: 39.8468,
        longitude: 33.5153,
      },
      {
        name: 'Batman',
        code: '72',
        region: 'Güneydoğu Anadolu',
        latitude: 37.8812,
        longitude: 41.1351,
      },
      {
        name: 'Şırnak',
        code: '73',
        region: 'Güneydoğu Anadolu',
        latitude: 37.5164,
        longitude: 42.4611,
      },
      {
        name: 'Bartın',
        code: '74',
        region: 'Karadeniz',
        latitude: 41.6344,
        longitude: 32.3375,
      },
      {
        name: 'Ardahan',
        code: '75',
        region: 'Doğu Anadolu',
        latitude: 41.1105,
        longitude: 42.7022,
      },
      {
        name: 'Iğdır',
        code: '76',
        region: 'Doğu Anadolu',
        latitude: 39.9167,
        longitude: 44.0333,
      },
      {
        name: 'Yalova',
        code: '77',
        region: 'Marmara',
        latitude: 40.65,
        longitude: 29.2667,
      },
      {
        name: 'Karabük',
        code: '78',
        region: 'Karadeniz',
        latitude: 41.2061,
        longitude: 32.6204,
      },
      {
        name: 'Kilis',
        code: '79',
        region: 'Güneydoğu Anadolu',
        latitude: 36.7184,
        longitude: 37.1212,
      },
      {
        name: 'Osmaniye',
        code: '80',
        region: 'Akdeniz',
        latitude: 37.0742,
        longitude: 36.2471,
      },
      {
        name: 'Düzce',
        code: '81',
        region: 'Karadeniz',
        latitude: 40.8438,
        longitude: 31.1565,
      },
    ];

    for (const city of cities) {
      const existingCity = await this.cityRepository.findOne({
        where: { code: city.code },
      });

      if (!existingCity) {
        await this.cityRepository.save({
          ...city,
          isActive: true,
        });
      }
    }
  }
}
