apiVersion: v1
kind: Service
metadata:
  name: library-auth-service
  labels:
    app: library-auth
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: library-auth


