import { DataSource } from 'typeorm';
import { config } from 'dotenv';
import { join } from 'path';

config();

const dataSource = new DataSource({
  type: 'postgres',
  host: 'yelekdunyasi.cdkugmi6qnk2.eu-north-1.rds.amazonaws.com',
  port: 5432,
  username: 'postgres',
  password: 'yelekdunyasi',
  database: 'postgres',
  entities: [join(__dirname, '..', 'cities', 'entities', '*.entity.{ts,js}')],
  synchronize: true,
  ssl: {
    rejectUnauthorized: false,
  },
});

async function runSeeders() {
  try {
    await dataSource.initialize();
    console.log('Veritabanı bağlantısı başarılı');

    const cities = [
      {
        name: 'Adana',
        code: '01',
        region: 'Akdeniz',
        latitude: 37,
        longitude: 35,
      },
      {
        name: 'Adıyaman',
        code: '02',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 38,
      },
      {
        name: 'Afyonkarahisar',
        code: '03',
        region: 'Ege',
        latitude: 38,
        longitude: 30,
      },
      {
        name: 'Ağrı',
        code: '04',
        region: 'Doğu Anadolu',
        latitude: 39,
        longitude: 43,
      },
      {
        name: 'Amasya',
        code: '05',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 35,
      },
      {
        name: 'Ankara',
        code: '06',
        region: 'İç Anadolu',
        latitude: 39,
        longitude: 32,
      },
      {
        name: 'Antalya',
        code: '07',
        region: 'Akdeniz',
        latitude: 36,
        longitude: 30,
      },
      {
        name: 'Artvin',
        code: '08',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 41,
      },
      { name: 'Aydın', code: '09', region: 'Ege', latitude: 37, longitude: 27 },
      {
        name: 'Balıkesir',
        code: '10',
        region: 'Marmara',
        latitude: 39,
        longitude: 27,
      },
      {
        name: 'Bilecik',
        code: '11',
        region: 'Marmara',
        latitude: 40,
        longitude: 29,
      },
      {
        name: 'Bingöl',
        code: '12',
        region: 'Doğu Anadolu',
        latitude: 38,
        longitude: 40,
      },
      {
        name: 'Bitlis',
        code: '13',
        region: 'Doğu Anadolu',
        latitude: 38,
        longitude: 42,
      },
      {
        name: 'Bolu',
        code: '14',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 31,
      },
      {
        name: 'Burdur',
        code: '15',
        region: 'Akdeniz',
        latitude: 37,
        longitude: 30,
      },
      {
        name: 'Bursa',
        code: '16',
        region: 'Marmara',
        latitude: 40,
        longitude: 29,
      },
      {
        name: 'Çanakkale',
        code: '17',
        region: 'Marmara',
        latitude: 40,
        longitude: 26,
      },
      {
        name: 'Çankırı',
        code: '18',
        region: 'İç Anadolu',
        latitude: 40,
        longitude: 33,
      },
      {
        name: 'Çorum',
        code: '19',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 34,
      },
      {
        name: 'Denizli',
        code: '20',
        region: 'Ege',
        latitude: 37,
        longitude: 29,
      },
      {
        name: 'Diyarbakır',
        code: '21',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 40,
      },
      {
        name: 'Edirne',
        code: '22',
        region: 'Marmara',
        latitude: 41,
        longitude: 26,
      },
      {
        name: 'Elazığ',
        code: '23',
        region: 'Doğu Anadolu',
        latitude: 38,
        longitude: 39,
      },
      {
        name: 'Erzincan',
        code: '24',
        region: 'Doğu Anadolu',
        latitude: 39,
        longitude: 39,
      },
      {
        name: 'Erzurum',
        code: '25',
        region: 'Doğu Anadolu',
        latitude: 39,
        longitude: 41,
      },
      {
        name: 'Eskişehir',
        code: '26',
        region: 'İç Anadolu',
        latitude: 39,
        longitude: 30,
      },
      {
        name: 'Gaziantep',
        code: '27',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 37,
      },
      {
        name: 'Giresun',
        code: '28',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 38,
      },
      {
        name: 'Gümüşhane',
        code: '29',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 39,
      },
      {
        name: 'Hakkari',
        code: '30',
        region: 'Doğu Anadolu',
        latitude: 37,
        longitude: 43,
      },
      {
        name: 'Hatay',
        code: '31',
        region: 'Akdeniz',
        latitude: 36,
        longitude: 36,
      },
      {
        name: 'Isparta',
        code: '32',
        region: 'Akdeniz',
        latitude: 37,
        longitude: 30,
      },
      {
        name: 'Mersin',
        code: '33',
        region: 'Akdeniz',
        latitude: 36,
        longitude: 34,
      },
      {
        name: 'İstanbul',
        code: '34',
        region: 'Marmara',
        latitude: 41,
        longitude: 28,
      },
      { name: 'İzmir', code: '35', region: 'Ege', latitude: 38, longitude: 27 },
      {
        name: 'Kars',
        code: '36',
        region: 'Doğu Anadolu',
        latitude: 40,
        longitude: 43,
      },
      {
        name: 'Kastamonu',
        code: '37',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 33,
      },
      {
        name: 'Kayseri',
        code: '38',
        region: 'İç Anadolu',
        latitude: 38,
        longitude: 35,
      },
      {
        name: 'Kırklareli',
        code: '39',
        region: 'Marmara',
        latitude: 41,
        longitude: 27,
      },
      {
        name: 'Kırşehir',
        code: '40',
        region: 'İç Anadolu',
        latitude: 39,
        longitude: 34,
      },
      {
        name: 'Kocaeli',
        code: '41',
        region: 'Marmara',
        latitude: 40,
        longitude: 29,
      },
      {
        name: 'Konya',
        code: '42',
        region: 'İç Anadolu',
        latitude: 37,
        longitude: 32,
      },
      {
        name: 'Kütahya',
        code: '43',
        region: 'Ege',
        latitude: 39,
        longitude: 29,
      },
      {
        name: 'Malatya',
        code: '44',
        region: 'Doğu Anadolu',
        latitude: 38,
        longitude: 38,
      },
      {
        name: 'Manisa',
        code: '45',
        region: 'Ege',
        latitude: 38,
        longitude: 27,
      },
      {
        name: 'Kahramanmaraş',
        code: '46',
        region: 'Akdeniz',
        latitude: 37,
        longitude: 36,
      },
      {
        name: 'Mardin',
        code: '47',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 40,
      },
      { name: 'Muğla', code: '48', region: 'Ege', latitude: 37, longitude: 28 },
      {
        name: 'Muş',
        code: '49',
        region: 'Doğu Anadolu',
        latitude: 38,
        longitude: 41,
      },
      {
        name: 'Nevşehir',
        code: '50',
        region: 'İç Anadolu',
        latitude: 38,
        longitude: 34,
      },
      {
        name: 'Niğde',
        code: '51',
        region: 'İç Anadolu',
        latitude: 37,
        longitude: 34,
      },
      {
        name: 'Ordu',
        code: '52',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 37,
      },
      {
        name: 'Rize',
        code: '53',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 40,
      },
      {
        name: 'Sakarya',
        code: '54',
        region: 'Marmara',
        latitude: 40,
        longitude: 30,
      },
      {
        name: 'Samsun',
        code: '55',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 36,
      },
      {
        name: 'Siirt',
        code: '56',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 41,
      },
      {
        name: 'Sinop',
        code: '57',
        region: 'Karadeniz',
        latitude: 42,
        longitude: 35,
      },
      {
        name: 'Sivas',
        code: '58',
        region: 'İç Anadolu',
        latitude: 39,
        longitude: 37,
      },
      {
        name: 'Tekirdağ',
        code: '59',
        region: 'Marmara',
        latitude: 40,
        longitude: 27,
      },
      {
        name: 'Tokat',
        code: '60',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 36,
      },
      {
        name: 'Trabzon',
        code: '61',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 39,
      },
      {
        name: 'Tunceli',
        code: '62',
        region: 'Doğu Anadolu',
        latitude: 39,
        longitude: 39,
      },
      {
        name: 'Şanlıurfa',
        code: '63',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 38,
      },
      { name: 'Uşak', code: '64', region: 'Ege', latitude: 38, longitude: 29 },
      {
        name: 'Van',
        code: '65',
        region: 'Doğu Anadolu',
        latitude: 38,
        longitude: 43,
      },
      {
        name: 'Yozgat',
        code: '66',
        region: 'İç Anadolu',
        latitude: 39,
        longitude: 34,
      },
      {
        name: 'Zonguldak',
        code: '67',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 31,
      },
      {
        name: 'Aksaray',
        code: '68',
        region: 'İç Anadolu',
        latitude: 38,
        longitude: 34,
      },
      {
        name: 'Bayburt',
        code: '69',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 40,
      },
      {
        name: 'Karaman',
        code: '70',
        region: 'İç Anadolu',
        latitude: 37,
        longitude: 33,
      },
      {
        name: 'Kırıkkale',
        code: '71',
        region: 'İç Anadolu',
        latitude: 39,
        longitude: 33,
      },
      {
        name: 'Batman',
        code: '72',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 41,
      },
      {
        name: 'Şırnak',
        code: '73',
        region: 'Güneydoğu Anadolu',
        latitude: 37,
        longitude: 42,
      },
      {
        name: 'Bartın',
        code: '74',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 32,
      },
      {
        name: 'Ardahan',
        code: '75',
        region: 'Doğu Anadolu',
        latitude: 41,
        longitude: 42,
      },
      {
        name: 'Iğdır',
        code: '76',
        region: 'Doğu Anadolu',
        latitude: 39,
        longitude: 44,
      },
      {
        name: 'Yalova',
        code: '77',
        region: 'Marmara',
        latitude: 40,
        longitude: 29,
      },
      {
        name: 'Karabük',
        code: '78',
        region: 'Karadeniz',
        latitude: 41,
        longitude: 32,
      },
      {
        name: 'Kilis',
        code: '79',
        region: 'Güneydoğu Anadolu',
        latitude: 36,
        longitude: 37,
      },
      {
        name: 'Osmaniye',
        code: '80',
        region: 'Akdeniz',
        latitude: 37,
        longitude: 36,
      },
      {
        name: 'Düzce',
        code: '81',
        region: 'Karadeniz',
        latitude: 40,
        longitude: 31,
      },
    ];

    const cityRepository = dataSource.getRepository('City');

    for (const city of cities) {
      const existingCity = await cityRepository.findOne({
        where: { code: city.code },
      });
      if (!existingCity) {
        await cityRepository.save({
          ...city,
          isActive: true,
        });
      }
    }

    console.log('Şehir verileri başarıyla eklendi');
    await dataSource.destroy();
    console.log('Veritabanı bağlantısı kapatıldı');
  } catch (error) {
    console.error('Seeder çalıştırılırken hata oluştu:', error);
    process.exit(1);
  }
}

runSeeders();
