export default () => ({
  app: {
    name: process.env.APP_NAME,
    version: process.env.APP_VERSION,
    apiPrefix: process.env.APP_API_PREFIX,
    port: parseInt(process.env.APP_PORT ?? '3000', 10),
    nodeEnv: process.env.APP_NODE_ENV,
    frontendDomain: process.env.APP_FRONTEND_DOMAIN,
    workingDirectory: process.env.APP_WORKING_DIRECTORY,
    fallbackLanguage: process.env.APP_FALLBACK_LANGUAGE,
    headerLanguage: process.env.APP_HEADER_LANGUAGE,
  },
  database: {
    type: process.env.DATABASE_TYPE,
    url: process.env.DATABASE_URL,
    host: process.env.DATABASE_HOST,
    port: parseInt(process.env.DATABASE_PORT ?? '5432', 10),
    username: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    name: process.env.DATABASE_NAME,
    synchronize: process.env.DATABASE_SYNCHRONIZE === 'true',
    maxConnections: parseInt(process.env.DATABASE_MAX_CONNECTIONS ?? '100', 10),
    sslEnabled: process.env.DATABASE_SSL_ENABLED === 'true',
    ca: process.env.DATABASE_CA,
    key: process.env.DATABASE_KEY,
    cert: process.env.DATABASE_CERT,
  },
  auth: {
    jwt: {
      secret: process.env.AUTH_JWT_SECRET,
      expiresIn: process.env.AUTH_JWT_EXPIRES_IN,
    },
    refreshSecret: process.env.AUTH_REFRESH_SECRET,
    refreshExpires: process.env.AUTH_REFRESH_EXPIRES_IN,
    expires: process.env.AUTH_EXPIRES,
  },
  google: {
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
  },
  facebook: {
    appId: process.env.FACEBOOK_APP_ID,
    appSecret: process.env.FACEBOOK_APP_SECRET,
  },
  twitter: {
    consumerKey: process.env.TWITTER_CONSUMER_KEY,
    consumerSecret: process.env.TWITTER_CONSUMER_SECRET,
  },
  apple: {
    appAudience: process.env.APPLE_APP_AUDIENCE,
  },
  mail: {
    host: process.env.MAIL_HOST,
    port: parseInt(process.env.MAIL_PORT ?? '587', 10),
    ignoreTLS: process.env.MAIL_IGNORE_TLS === 'true',
    secure: process.env.MAIL_SECURE === 'true',
    requireTLS: process.env.MAIL_REQUIRE_TLS === 'true',
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASSWORD,
    defaultName: process.env.MAIL_DEFAULT_NAME,
    defaultEmail: process.env.MAIL_DEFAULT_EMAIL,
  },
  mailjet: {
    apiKey: process.env.MAILJET_API_KEY,
    apiSecret: process.env.MAILJET_API_SECRET,
    fromEmail: process.env.MAILJET_FROM_EMAIL,
    fromName: process.env.MAILJET_FROM_NAME,
  },
  oneSignal: {
    appId: process.env.ONE_SIGNAL_APP_ID,
    restApiKey: process.env.ONE_SIGNAL_REST_API_KEY,
    apiUrl: process.env.ONE_SIGNAL_API_URL,
  },
  netgsm: {
    username: process.env.NETGSM_USERNAME,
    password: process.env.NETGSM_PASSWORD,
    header: process.env.NETGSM_HEADER,
  },
  file: {
    driver: process.env.FILE_DRIVER,
    maxFileSize: parseInt(process.env.FILE_MAX_FILE_SIZE ?? '5242880', 10),
    awsS3Region: process.env.FILE_AWS_S3_REGION,
    accessKeyId: process.env.FILE_ACCESS_KEY_ID,
    secretAccessKey: process.env.FILE_SECRET_ACCESS_KEY,
    awsDefaultS3Bucket: process.env.FILE_AWS_DEFAULT_S3_BUCKET,
  },
});
